name: Times2Twitter

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        uses: garygrossgarten/github-action-ssh@v0.3.0
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USER }}
          privateKey: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.HOST_PORT }}
          command: cd ${{ secrets.dir }} && git pull origin master && docker build -t t2t:1.5 . --force-rm=true --no-cache && docker stop t2t && docker rm t2t && docker run -d -it --env  SlackBtoken=${{ secrets.Bot_Token }} --name t2t t2t:1.5
